### ISSUE TITLE
Window title

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/lxqt-powermanagement#120]
https://github.com/lxqt/lxqt-powermanagement/blob/b4a71f4088c0a47c9e6b0149f965c272b4751978/config/idlenesswatchersettings.ui#L14
Is it correct? How should I understand and/or translate it?

**Comment by tsujan** [comment]
Qt Linguist has a `Sources and Forms` dock that shows the source (in the GUI, for example). I think Weblate has a similar capability.

Very rarely, some strings may not be important, in which case, you could leave them as they are.
