### ISSUE TITLE
ask user to poweroff on power button press event

### ISSUE THREAD

**Issue by cypa** [lxqt/lxqt-powermanagement#144]
How do I config this behaviour - ask user to poweroff on power button press event.
Now if I accidentally press power button laptop immediately powers off.

~λ systemd-inhibit --list
WHO                 UID  USER PID COMM            WHAT              WHY                        MODE 
UPower              0    root 536 upowerd         sleep             Pause device polling       delay
lxqt-powermanagment 1000 cypa 552 lxqt-powermanag handle-lid-switch LidWatcher is in da house! block

**Comment by luis-pereira** [comment]
Done in 0.16
