### ISSUE TITLE
Show Remaining Time

### ISSUE THREAD

**Issue by Crochet-bloke** [lxqt/lxqt-powermanagement#175]
Is there any way of displaying the remaining time left on the battery/charge icon, as well as the percentage. Or if there isn't perhaps it could be added in a future release?

I know a lot can depend on what applications are in use, but as a general guide - especially when first logging in - it could be quite useful.

Cheers!

**Comment by tsujan** [comment]
It's very impossible. The remaining time depends not only on how the computer is used but also on the battery itself.
