### ISSUE TITLE
Backlight change when computer is idle

### ISSUE THREAD

**Issue by selairi** [lxqt/lxqt-powermanagement#188]
Hello, I have just written a simple tool to change the backlight of the display when the computer is idle:

![idle-config](https://user-images.githubusercontent.com/1163139/78582781-1be85700-7836-11ea-9be9-14784e34f4c4.png)

This is in:
[https://github.com/selairi/lxqt-powermanagement](https://github.com/selairi/lxqt-powermanagement)

I think this could be useful for lxqt-powermanager, because it lets you save some battery of your laptop.

If there aren't suggestions, I will do a pull request.

Thanks.

**Comment by tsujan** [comment]
Great! This is really needed.

**Comment by selairi** [comment]
I'm think that is better with this plugin:
[https://github.com/lxqt/lxqt-panel/pull/1385](https://github.com/lxqt/lxqt-panel/pull/1385)

**Comment by tsujan** [comment]
> I'm think that is better with this plugin

IMHO, its place is good but you've written the code and you know what's best for it.

**Comment by selairi** [comment]
Sorry, but a I have a question:

I have been busy with my work and have been unable to work at LXQt. Now, I don't know if the process to merge pull request in the master branch has changed. Should I merge by myself my pull request (PR) in master branch when someone give me the "Good To Merge" ("GTM")?
When I sent a PR in the past, @agaida usually merged it. Has something changed? I have this message in [https://github.com/lxqt/lxqt-config/pull/579](https://github.com/lxqt/lxqt-config/pull/579):

>  @selari - please remove the conflicts and merge

Finally, the [https://lxqt.org/](https://lxqt.org/) doesn't work. Who is working on it?

Thanks.

**Comment by tsujan** [comment]
> Should I merge by myself my pull request (PR) in master branch when someone give me the "Good To Merge" ("GTM")?

After a GTM, you could.

> When I sent a PR in the past, @agaida usually merged it. Has something changed?

@agaida hasn't been around for a while.

**Comment by selairi** [comment]
@tsujan  Thanks

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/lxqt-powermanagement/pull/189
