### ISSUE TITLE
[Feature Request] Battery percentage

### ISSUE THREAD

**Issue by rcastill** [lxqt/lxqt-powermanagement#231]
Can you consider adding an option for showing the battery percentage next to the icon? Maybe I could do a PR?

I found #175 and OP asked for remaining time + percentage. I understand remaining time is not possible, but battery percentage was not addressed by the response.

**Comment by tsujan** [comment]
The tray icon shows the battery percentage.

**Comment by rcastill** [comment]
I meant next to. What happens if the user chooses to use system icons instead of the custom one?

**Comment by tsujan** [comment]
> What happens if the user chooses to use system icons instead of the custom one?

Then, he may want to use a good icon set compatible with Qt environments.

**Comment by ahmadraniri1994** [comment]
Check this @rcastill , [Lxqt precentage icon.](https://www.reddit.com/r/Lubuntu/comments/ic1223/lubuntu_2004_battery_percent_indicator/)

**Comment by stefonarch** [comment]
![schermata-01-13-11-11](https://user-images.githubusercontent.com/10681413/149310491-8f25d232-00b3-466d-b086-881278b97983.png)

Or just use "custom command plugin":

` upower -i /org/freedesktop/UPower/devices/battery_BAT0|grep percent|awk {'print $2'}

`
