### ISSUE TITLE
[feautre request] Inversion of the Circle

### ISSUE THREAD

**Issue by M4k51** [lxqt/lxqt-powermanagement#247]
In any applications, such a circle has specific logic (counterclockwise decreases, clockwise arrives). Your circle breaks conventional logic, causing confusion. I hope you will fix it in the future. 
![Power_Plugin](https://user-images.githubusercontent.com/82149814/114020285-1920a780-9878-11eb-815c-e03d450cf55b.png)

**Comment by tsujan** [comment]
"Preference" and "logic" aren't synonymous. There's nothing to fix here.

P.S.
I'd transfer this page to Discussions if its button hadn't disappeared again.
