### ISSUE TITLE
Battery monitor settings disabled only on first run

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-powermanagement#272]
At first login on a machine without battery a info is displayed: "Could not find any battery, battery monitor disabled" and it works.

But when checking later the corresponding box in lxqt-config-powermanagement the same message will show up immediately, but the checkbox will remain checked. At next login the same message will be showed again, until the user manually disables it.

##### Expected Behavior

According to the message, it should be disabled in the setting.
##### Current Behavior

It is always active
##### Possible Solution

Do not show any battery or lid related setting (or only greyed out) when  no lid and/or no battery is present, as in https://github.com/lxqt/lxqt-powermanagement/issues/261
##### Steps to Reproduce (for bugs)

1. On a PC Desktop or in Virtualbox activate battery monitor.
2. A message will be displayed, saying it will be disabled.
3. Control the settings, still active
4. Restart session, again the message and no result.

                           

##### System Information

* Distribution & Version: latest git, all prior versions probably

**Comment by tsujan** [comment]
The report is very old and unattended. Frankly, I don't get what was the problem. When you check it, you want it; there's no reason for it to be unchecked automatically (think of an old laptop whose battery is temporarily removed).
