### ISSUE TITLE
Presentation mode

### ISSUE THREAD

**Issue by tenplus1** [lxqt/lxqt-powermanagement#274]
Would it be possible to add a "Presentation Mode" feature to the power tray icon so that users can disable suspend/hibernate/screen blanking ?

**Comment by tsujan** [comment]
The tray icon already has a Configure menu item. You can change everything from there.

**Comment by tsujan** [comment]
Or you may have made a duplicate report, meaning https://github.com/lxqt/lxqt-powermanagement/issues/253. It's already implemented.
