### ISSUE TITLE
[Feature Request] Add custom command to run before suspend

### ISSUE THREAD

**Issue by georgebushdown** [lxqt/lxqt-powermanagement#283]
### lxqt-config-powermanagement
![lxqt](https://user-images.githubusercontent.com/39475970/135493309-4583eb31-a133-45e9-965c-5f29a91db964.png)

I set up auto-suspend when the laptop power level reaches a level. I'm using slock to lock the screen on demand and would like it to be run before the auto-suspend.

Can you add a box for putting a custom command before suspending?

**Comment by stefonarch** [comment]
It's not necessary for this: you can use xautolock and the setting in `Session Settings > lock screen before suspend`. I'm using i3lock with this setup.
https://github.com/lxqt/lxqt/wiki/ConfigScreensavers#other-screenlockers-using-xautolock

**Comment by georgebushdown** [comment]
Oh I didn't know about this page, thanks.

**Comment by georgebushdown** [comment]
I don't see any lxqt modules in the list.

**Comment by stefonarch** [comment]
> I don't see any lxqt modules in the list. What could be the issue?

Sorry, I don't  understand: which list?  Why a module?

**Comment by georgebushdown** [comment]
Under lxqt-config-sessions.

**Comment by stefonarch** [comment]
No idea, never seen this. But it's not related to this feature request. 
My 2 cents; testing a new clean user, and if you can repeat the problem open an issue.

**Comment by georgebushdown** [comment]
Not related? The wiki article tells to look in lxqt session settings, which is what I did.

**Comment by stefonarch** [comment]
The modules should be listed sure, but you need this  option not a module:

![schermata-10-01-07-57](https://user-images.githubusercontent.com/10681413/135572853-0bc2d98f-9d57-4cb4-a77e-d16160ece727.png)

**Comment by georgebushdown** [comment]
![lxqtsession](https://user-images.githubusercontent.com/39475970/135618861-dccb5fbd-b767-4af5-ac08-5bcc2053b0c6.png)

Initially I did, but there was no effect. Turns out there was an issue with `xautolock`. I switched to `xss-lock` instead and it started working. Thanks.
