### ISSUE TITLE
Error installation v1.0.0

### ISSUE THREAD

**Issue by manurare** [lxqt/lxqt-powermanagement#300]
Hi,

`lxqt-powermanagement` stopped showing the double battery icon for dual battery machines as my Thinkpad therefore I have installed the last version of `lxqt-powermanagement` but without success. Now, `lxqt-powermanagement` is not working at all.

When executing `lxqt-config-powermanagement`

`lxqt-config-powermanagement: error while loading shared libraries: liblxqt.so.1: cannot open shared object file: No such file or directory`

However `liblxqt.so.1` exists in ` /usr/local/lib/liblxqt.so.1` . Have I installed anything wrong? Also any idea why one year ago the two battery icons showed up but since last month they decide to not show up again? Onky the main battery one is showing.

* Distribution & Version: Ubuntu 21.10
* Kernel: 5.13.0.27.37
* Qt Version: 5.15.2
* liblxqt Version: 0.17.0
* lxqt-build-tools Version: 0.9.0
* Package version: 1.0.0?

**Comment by tsujan** [comment]
> Have I installed anything wrong?

Latest lxqt-powermanagement needs latest LXQt. Components may not work after installing incompatible versions.

> Also any idea why one year ago the two battery icons showed up but since last month they decide to not show up again?

lxqt-powermanagement is a front-end for `solid` (belonging to `kf5`) and gets the info from it.
