### ISSUE TITLE
[Feature request] Show Remaining Time (again)

### ISSUE THREAD

**Issue by ceever** [lxqt/lxqt-powermanagement#360]
##### Context
I know this has already been discussed before under #175. But since it is such a useful feature also available with Windows, I would like to propose to just use the information about the remaining time (for charging or discharging) from *upower*:
```bash
upower -i $(upower -e | grep '/battery') | grep --color=never -E "to\ full|to\ empty"
```

I actually currently have a keyboard shortcut defined, which extracts the relevant information from *upower* and then triggers a notification with the relevant information displayed. 🤷

![20230219 215534_rectangle_281x129](https://user-images.githubusercontent.com/40247591/219974679-1d22c671-db12-4801-9696-54e9f723a6af.png)

##### Expected Behavior
1. Show remaining time (for charging or discharging) when hovering over the battery icon in the panel with the mouse.
2. Add an option to Powermanagement to have this time displayed on mouseover.

##### Current Behavior
Neither.

##### Possible Solution
Leverage *upower*.

##### Steps to Reproduce (for bugs)
1. Hover over the battery icon shown in the LXQt panel. 

##### System Information

* Distribution & Version: Ubuntu 22.10
* Kernel: lubuntu 5.19.0-21-generic
* Qt Version: 5.15.6
* liblxqt Version: ?
* lxqt-build-tools Version: ?
* Package version: ?

**Comment by tsujan** [comment]
You mean something other than this tooltip?

![tooltip](https://user-images.githubusercontent.com/981076/219975373-78bdf490-8cef-4226-addd-b695f12dcfa5.png)

**Comment by ceever** [comment]
Ups ... 😅 ... this wasn't just there when I checked it.

My bad. Thx 🙏

**Comment by tsujan** [comment]
Frankly, I don't remember how `solid` worked 4 years ago (when I closed the other report). Anyway, it gives both time-to-empty and time-to-full, and they're shown on the tooltip.
