### ISSUE TITLE
Not working monitor actions if on wayland

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-powermanagement#403]
In the configuration actions for turning monitor(s) off can be set on idle and lid close and those won't work on wayland
##### Expected Behavior

Showed actions are working.
##### Current Behavior

Monitor actions aren't.
##### Possible Solution

Or disable/grey out those actions or implement what [wlopm](https://git.sr.ht/~leon_plickat/wlopm) uses:
https://wayland.app/protocols/wlr-output-power-management-unstable-v1#zwlr_output_power_manager_v1

##### System Information

* Distribution & Version: git,arch,all

**Comment by tsujan** [comment]
It depends on the compositor. → [Wayland Wiki](https://github.com/lxqt/lxqt/wiki/ConfigWaylandSettings#turning-off-monitor-when-idle-with-kwin)
